import { describe, expect, it } from 'vitest';
import { buildInfo } from '../src/shared/config/buildInfo';
import { KAIROS_BACKUP_FORMAT_NAME, KAIROS_BACKUP_FORMAT_VERSION, KairosBackupValidationError, createKairosBackupEnvelope, parseKairosBackup, serializeKairosBackup, validateKairosBackupEnvelope } from '../src/data/backup';

describe('P6 backup envelope compatibility under P9.2', () => {
 const metadata=[{key:'theme',value:'dark',updatedAt:'2026-08-31T08:00:00.000Z'}];
 it('creates current V6-format full-backup envelope with schema V7',()=>{const e=createKairosBackupEnvelope({metadata,exportedAt:new Date('2026-08-31T08:30:00.000Z'),appVersion:'test-app',buildId:'test-build'});expect(e).toMatchObject({formatName:KAIROS_BACKUP_FORMAT_NAME,formatVersion:9,databaseSchemaVersion:10,recordCounts:{metadata:1,trades:0,tradePlans:0,tradeExecutions:0,tradeFees:0,savedAnalyses:0,savedTimeAssistedSnapshots:0,tradeDiscipline:0,total:1}});});
 it('round-trips current V4 JSON',()=>{const e=createKairosBackupEnvelope({metadata});expect(parseKairosBackup(serializeKairosBackup(e))).toEqual(e);});
 it('accepts and migrates an existing V2-format schema V2 backup after later schema upgrades',()=>{const legacyV2={formatName:KAIROS_BACKUP_FORMAT_NAME,formatVersion:2,appVersion:'old-v2',buildId:'old-v2',exportedAt:'2026-08-31T08:30:00.000Z',databaseSchemaVersion:2,recordCounts:{metadata:1,trades:0,tradePlans:0,tradeExecutions:0,tradeFees:0,total:1},payload:{metadata,trades:[],tradePlans:[],tradeExecutions:[],tradeFees:[]}};expect(parseKairosBackup(JSON.stringify(legacyV2))).toMatchObject({formatVersion:9,databaseSchemaVersion:10,recordCounts:{metadata:1,savedAnalyses:0,savedTimeAssistedSnapshots:0,tradeDiscipline:0,total:1}});});
 it('accepts and migrates legacy V1 metadata-only backup to current V6 restore model',()=>{const legacy={formatName:KAIROS_BACKUP_FORMAT_NAME,formatVersion:1,appVersion:'old',buildId:'old',exportedAt:'2026-08-31T08:30:00.000Z',databaseSchemaVersion:1,recordCounts:{metadata:1,total:1},payload:{metadata}};const migrated=parseKairosBackup(JSON.stringify(legacy));expect(migrated).toMatchObject({formatVersion:9,databaseSchemaVersion:10,recordCounts:{metadata:1,trades:0,savedAnalyses:0,savedTimeAssistedSnapshots:0,tradeDiscipline:0,total:1}});expect(migrated.payload.metadata).toEqual(metadata);});
 it('rejects unsupported future format versions and malformed payloads',()=>{const e=createKairosBackupEnvelope({metadata});expect(()=>validateKairosBackupEnvelope({...e,formatVersion:10})).toThrowError(expect.objectContaining({code:'UNSUPPORTED_FORMAT_VERSION'}));expect(()=>validateKairosBackupEnvelope({...e,payload:{...e.payload,trades:[{}]}})).toThrow(KairosBackupValidationError);});
});
