import 'fake-indexeddb/auto';
import Dexie from 'dexie';
import { afterEach, describe, expect, it } from 'vitest';
import { createKairosDatabase, openKairosDatabase, runKairosAtomicWrite, assertKairosDatabaseIntegrity } from '../src/data/database';
import { createKairosRepositories } from '../src/data/repositories';
import { createTradeDomainId, parsePositiveDecimalString, type TradeExecutionId, type TradeFeeId, type TradeId, type TradePlanId } from '../src/domain/trades';
const names=new Set<string>(); const name=(x:string)=>{const n=`kairos-p92-${x}-${crypto.randomUUID()}`;names.add(n);return n};
afterEach(async()=>{for(const n of names){await new Promise<void>((res,rej)=>{const q=indexedDB.deleteDatabase(n);q.onsuccess=()=>res();q.onerror=()=>rej(q.error);q.onblocked=()=>rej(new Error('blocked'));});}names.clear();});
const dec=(v:string)=>{const p=parsePositiveDecimalString(v);if(!p.ok)throw new Error('fixture decimal');return p.value};
const fixture=()=>{const tradeId=createTradeDomainId<TradeId>();const executionId=createTradeDomainId<TradeExecutionId>();return {trade:{id:tradeId,symbol:'AAPL',marketType:'stock' as const,side:'long' as const,status:'open' as const,source:'manual' as const,openedAt:'2026-09-01T00:00:00.000Z',closedAt:null,createdAt:'2026-09-01T00:00:00.000Z',updatedAt:'2026-09-01T00:00:00.000Z'},plan:{id:createTradeDomainId<TradePlanId>(),tradeId,plannedEntryPrice:dec('100'),plannedStopPrice:dec('95'),plannedTargetPrice:dec('110'),plannedQuantity:dec('2'),createdAt:'2026-09-01T00:00:00.000Z',updatedAt:'2026-09-01T00:00:00.000Z'},execution:{id:executionId,tradeId,type:'entry' as const,price:dec('101.25'),quantity:dec('2'),executedAt:'2026-09-01T00:01:00.000Z',createdAt:'2026-09-01T00:01:00.000Z'},fee:{id:createTradeDomainId<TradeFeeId>(),tradeId,executionId,amount:dec('1.5'),currency:'USD',createdAt:'2026-09-01T00:01:00.000Z'}}};
describe('P9.2 trade persistence',()=>{
 it('upgrades immutable v1 metadata fixture to current schema without losing data',async()=>{const n=name('upgrade');const old=new Dexie(n);old.version(1).stores({metadata:'&key'});await old.open();await old.table('metadata').put({key:'legacy',value:'kept',updatedAt:'2026-08-31T00:00:00.000Z'});old.close();const db=createKairosDatabase(n);await openKairosDatabase(db);expect(db.verno).toBe(8);await expect(db.metadata.get('legacy')).resolves.toMatchObject({value:'kept'});expect(db.tables.map(t=>t.name).sort()).toEqual(['metadata','savedAnalyses','savedTimeAssistedSnapshots','tradeDiscipline','tradeExecutions','tradeFees','tradePlans','trades'].sort());db.close();const reload=createKairosDatabase(n);await openKairosDatabase(reload);await expect(reload.metadata.get('legacy')).resolves.toMatchObject({value:'kept'});reload.close();});
 it('commits one trade aggregate atomically through repositories',async()=>{const db=createKairosDatabase(name('atomic'));await openKairosDatabase(db);const f=fixture();await runKairosAtomicWrite(db,['trades','tradePlans','tradeExecutions','tradeFees'],async({repositories})=>{await repositories.trades.put(f.trade);await repositories.tradePlans.put(f.plan);await repositories.tradeExecutions.put(f.execution);await repositories.tradeFees.put(f.fee);});const repos=createKairosRepositories(db);await expect(repos.tradeExecutions.listByTradeId(f.trade.id)).resolves.toHaveLength(1);await expect(assertKairosDatabaseIntegrity(db)).resolves.toMatchObject({ok:true,tradeRecordCount:1});db.close();});
 it('rolls back the whole aggregate on failure',async()=>{const db=createKairosDatabase(name('rollback'));await openKairosDatabase(db);const f=fixture();await expect(runKairosAtomicWrite(db,['trades','tradePlans'],async({repositories})=>{await repositories.trades.put(f.trade);await repositories.tradePlans.put(f.plan);throw new Error('fail');})).rejects.toThrow('fail');expect(await db.trades.count()).toBe(0);expect(await db.tradePlans.count()).toBe(0);db.close();});
 it('detects orphan trade references instead of repairing them',async()=>{const db=createKairosDatabase(name('orphan'));await openKairosDatabase(db);const f=fixture();await db.tradeExecutions.put(f.execution);await expect(assertKairosDatabaseIntegrity(db)).rejects.toThrow('trade-reference-integrity');expect(await db.tradeExecutions.count()).toBe(1);db.close();});
});
